import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";

const latoSans = Lato({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark bg-[#DAE1E9]">
      <body
        className={`${latoSans.className} antialiased min-h-screen max-w-[640px] mx-auto`}
      >
        {children}
      </body>
    </html>
  );
}
